name: Test

on: [push]

jobs:
  build-and-pr:
    name: "Build and PR"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: "npm install"
      - name: Run hardhat tests
        run: "npm run-script test"
      - name: Run lint checks
        run: "npm run-script lint"
